[cache]
dir = "/Users/takuma/.local/share/tlrc"
# dir = "$XDG_DATA_HOME/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = ["en"]

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
compact = false
raw_markdown = false

[indent]
title = 0
description = 0
bullet = 2
example = 4

[style.title]
color = "white"
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
color = "white"
# color = "cyan"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = "green"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
# color = "cyan"
color = { color256 = 204 }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color = "white"
background = "default"
bold = false
underline = true
italic = true
dim = false
strikethrough = false

[style.inline_code]
color = "yellow"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
# color = "red"
color = "white"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false
