#!/usr/bin/env bash

if type brew > /dev/null 2>&1; then
  echo "Homebrew is already installed."
else
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Installing formulae and casks"
brew bundle install --file ../packages/homebrew/Brewfile

