[directories]
cache_dir        = "/Users/takuma/.cache/tealdeer/"
custom_pages_dir = "/Users/takuma/.local/share/tealdeer/custom-tldr-pages/"

[updates]
auto_update = false

[display]
compact   = false
use_pager = false

[style.command_name]
foreground = { ansi = 204 }
bold = true

[style.description]
foreground = "white"

[style.example_text]
foreground = "green"

[style.example_code]
foreground = { ansi = 204 }
# foreground = "white"
# bold = true

[style.example_variable]
# foreground = "white"
# bold = true
# underline = true


